/* tslint:disable */
/* eslint-disable */
/**
 * StudentMeal.GlobalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { send } from "../base2"

/**
 * ConfigApi - API class
 */
export class ConfigApi {
    /**
     * 
     * @summary 查询配置信息
     * @param string hwcode 
     */
    public Config(hwcode: string): Promise<{ [key: string]: any; }> {
        return send({
            url: '/config',
            method: 'GET',
            headers: {
                hwcode: hwcode,
            },
        });
    }
}

/**
 * ConfigApi - instance
 */
export const ConfigApiInstance = new ConfigApi();

