/* tslint:disable */
/* eslint-disable */
/**
 * StudentMeal.GlobalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { send } from "../base2"

/**
 * HeartBeatApi - API class
 */
export class HeartBeatApi {
    /**
     * 
     * @summary 心跳检查
     * @param string hwcode 
     */
    public HeartBeat(hwcode: string): Promise<void> {
        return send({
            url: '/HeartBeat',
            method: 'GET',
            headers: {
                hwcode: hwcode,
            },
        });
    }
}

/**
 * HeartBeatApi - instance
 */
export const HeartBeatApiInstance = new HeartBeatApi();

