/* tslint:disable */
/* eslint-disable */
/**
 * StudentMeal.GlobalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { send } from "../base2"
import type { RouteInfo } from "../models"

/**
 * RouteApi - API class
 */
export class RouteApi {
    /**
     * 
     * @summary 获取硬件的配置信息
     * @param string hwcode 
     */
    public Route(hwcode: string): Promise<RouteInfo> {
        return send({
            url: '/route',
            method: 'GET',
            params: {
                hwcode: hwcode,
            },
        });
    }
}

/**
 * RouteApi - instance
 */
export const RouteApiInstance = new RouteApi();

