/* tslint:disable */
/* eslint-disable */
/**
 * StudentMeal.GlobalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { send } from "../base2"
import type { AppversionInfo } from "../models"

/**
 * UpgradeApi - API class
 */
export class UpgradeApi {
    /**
     * 
     * @summary 获取最近一次的升级的版本信息
     * @param string appName 
     * @param string hwcode 
     * @param boolean? manual 
     */
    public Upgrade(appName: string, hwcode: string, manual?: boolean): Promise<AppversionInfo> {
        return send({
            url: '/upgrade',
            method: 'GET',
            params: {
                appName: appName,
                hwcode: hwcode,
                manual: manual,
            },
        });
    }
}

/**
 * UpgradeApi - instance
 */
export const UpgradeApiInstance = new UpgradeApi();

