/* tslint:disable */
/* eslint-disable */
/**
 * StudentMeal.GlobalService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RouteInfo {
    'baseUrl'?: string | null;
    'imageUrl'?: string | null;
    'publicUrl'?: string | null;
    'schoolUrl'?: string | null;
    'appUrl'?: string | null;
    'supplierUrl'?: string | null;
    'imageProxyUrl'?: string | null;
    'appImageUrl'?: string | null;
    'hardwareCode'?: string | null;
    'hardwareType'?: string | null;
}

